using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Problems
{
    /*
        Each new term in the Fibonacci sequence is generated by adding the previous two terms. 
        By starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
        By considering the terms in the Fibonacci sequence whose values do not exceed four million, 
        find the sum of the even-valued terms.
    */
    public class Problem_002
    {
        public static void Run()
        {
            int sum = 0;

            int f_previous = 0;
            int f_current = 1;
            while (f_current <= 4000000)
            {
                // If even number, do the sum
                if (f_current % 2 == 0) sum += f_current;

                // Calculate the new Fibonacci sequence
                int temp = f_current;
                f_current += f_previous;
                f_previous = temp;
            }

            Debug.WriteLine("The answer is " + sum);
        }
    }
}
